[versions]
# Build details
compileSdk = "35"
targetSdk = "35"
minSdk = "23"
versionCode = "1721768587"
versionName = "2.3.0"

# BoM
composeBom = "2025.05.00"
koinBom = "4.0.2"

# Libraries
androidLifecycle = "2.9.0"
androidTestEspresso = "3.6.1"
androidTestJunit = "1.2.1"
appcompat = "1.7.0"
composeLivedata = "1.8.1"
composeNavigation = "2.9.0"
junit = "4.13.2"
kotlinCore = "1.16.0"

# Plugins
androidGradlePlugin = "8.8.2"
kotlinPlugins = "2.1.10"
ktlintPlugin = "12.2.0"

[libraries]
android-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
android-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidLifecycle" }
android-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidTestEspresso" }
android-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidTestJunit" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "composeLivedata" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-tooling-base = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koinBom" }
koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-core = { group = "io.insert-koin", name = "koin-core" }
koin-compose-base = { group = "io.insert-koin", name = "koin-androidx-compose" }
kotlin-core = { group = "androidx.core", name = "core-ktx", version.ref = "kotlinCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinPlugins" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinPlugins" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPlugin" }
